### ISSUE TITLE
Content inset top on iPhone 6

### ISSUE THREAD

**Issue by bmancone** [uzysjung/UzysCircularProgressPullToRefresh#12]
Hi,

First I'd like to thank you for your awesome lib I've been using it for months now and never had to complain ! :smile: 

Unfortunately, today, I'm having an issue with an iPhone 6.

Once the animation stops, it looks like the `contentInset.top` changed resulting in a large white space before the cells.

I tracked down the issue to this [line of code](https://github.com/uzysjung/UzysCircularProgressPullToRefresh/blob/1.0.8/UzysCircularProgressPullToRefresh/UzysCircularProgressPullToRefresh/Library/UIScrollView%2BUzysCircularProgressPullToRefresh.m#L54). By using 64.00 like it was before iOS8, the issue seems to be solved. 

If it helps, I have an `UITableViewController` embedded in a container view

Thanks for looking it !

Br,

**Comment by albertschulz** [comment]
Yes, I think this is right.
```
view.portraitTopInset = 64.0;
```
